// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezlaNg1fTuC365q90-lyzlketR59i4w8',
    appId: '1:743991759074:web:d73bf4c77246ec54764ebb',
    messagingSenderId: '743991759074',
    projectId: 'ferrous-arena-356017',
    authDomain: 'ferrous-arena-356017.firebaseapp.com',
    databaseURL: 'https://ferrous-arena-356017-default-rtdb.firebaseio.com',
    storageBucket: 'ferrous-arena-356017.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSo7B3XVqnJqjd_kuzdwa0Z-yrn-AYDs',
    appId: '1:743991759074:android:971ec7f715757a85764ebb',
    messagingSenderId: '743991759074',
    projectId: 'ferrous-arena-356017',
    databaseURL: 'https://ferrous-arena-356017-default-rtdb.firebaseio.com',
    storageBucket: 'ferrous-arena-356017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9cuUGFc0Tzdu9Ef-TybRopCnjs0-1sU',
    appId: '1:743991759074:ios:43b04d455b06a753764ebb',
    messagingSenderId: '743991759074',
    projectId: 'ferrous-arena-356017',
    databaseURL: 'https://ferrous-arena-356017-default-rtdb.firebaseio.com',
    storageBucket: 'ferrous-arena-356017.appspot.com',
    androidClientId: '743991759074-2vrl00qqsmu67qiko03vognpmc2acb13.apps.googleusercontent.com',
    iosClientId: '743991759074-k1ehgkj8ghg32ilq5rsls0pkq0dc84ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberRiderApp',
  );
}
